---
driver:
  name: vagrant
  customize:
        cableconnected1: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[demo-cookbook::default]
    attributes:
