language: ruby
notifications:
  email: false
  slack:
    secure: PutYourSlackAPITokenHere
sudo: false

dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

bundler_args: --without='vagrant'

install:
  - cd ./demo-cookbook
  - gem install bundler

branches:
  only:
    - master

services: docker

env:
  - INSTANCE=ubuntu-1604

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script:
  # Fake 'localhost' to go back to docker host
  - sed -e '/localhost/d' /etc/hosts > /var/tmp/hosts.new
  - cp /var/tmp/hosts.new /etc/hosts
  - echo "$(ip route | grep default | awk '{print $3}') localhost" >> /etc/hosts
  # Run index to make some tetchy gems work
  - bundle --full-index
  # Test suite
  - bundle exec rake travis
